### ISSUE TITLE
clarify what happens during cleanup

### ISSUE THREAD

**Issue by StefanoSalsano** [ferrarimarco/kubernetes-playground#105]
several warnings are presented during a "--provision-with cleanup"

for example

1) k8s-master-1.k8s-p9.local: W0323 01:35:19.650319   18139 removeetcdmember.go:61] [reset] failed to remove etcd member: error syncing endpoints with etc: etcdclient: no available endpoints
    k8s-master-1.k8s-p9.local: .Please manually remove this etcd member using etcdctl

2) The reset process does not clean CNI configuration. To do so, you must remove /etc/cni/net.d

at least we should also output a message saying that we have taken care and that this is not an issue

**Comment by ferrarimarco** [comment]
@StefanoSalsano 

1. Is the warning something we've to care about?
1. The second point doesn't apply anymore, [right](https://github.com/ferrarimarco/kubernetes-playground/blob/master/scripts/linux/cleanup-k8s-and-cni.sh#L26)?

**Comment by ferrarimarco** [comment]
Actually, it turns out that this is a more complex issue.

We should run the `cleanup` provisioner on worker nodes before running it on the master node AND we should clarify (with some echoes) that we take care of the rest of the cleanup.
