### ISSUE TITLE
clarify the relationship between k8s-playground and kites project

### ISSUE THREAD

**Issue by StefanoSalsano** [ferrarimarco/kubernetes-playground#110]
kites project is using k8s-playground, but it should not necessarily contribute to the core part... it has a folder kubernetes/net-tests (which could become kubernetes/kites) and this is ok, because in this folder we contribute yaml that can be used to deploy pods and services over the basic infrastructure

the kubernetes/kites folder can be seen as contribution of kites project to k8s-playground (or it can be seen as k8s-playground selecting another use case to run over the playground)

how should we consider the deployment of the containers that we are currently putting in docker/net-test ?? is it better to have them in a separate repo ?

more in general can we have separate "plugins" to be integrated into k8s-playground?

**Comment by ferrarimarco** [comment]
I think that for now we should have a plugins/extensions/use cases/whatever folder, to not complicate maintenance. Then, when the core is stable, we might move kubernetes-playground to a dedicate kites organization, and move the extensions out of this repo to dedicated ones.

And yes, I think we should name the directory `kites`.

**Comment by StefanoSalsano** [comment]
ok I agree! 
and I'll rename the folder in the PR #109

**Comment by StefanoSalsano** [comment]
with PR #141 I created a folder ext with a README.md and a .gitignore, so that projects can create their own folders without interfering with k8s-playground
