### ISSUE TITLE
Simplify UDP/TCP Tests

### ISSUE THREAD

**Issue by simonezacca** [ferrarimarco/kubernetes-playground#117]
they're described here
https://docs.google.com/document/d/1PIgGRPOhttMnefnZwscTuZYGbaIm21gX3Zr-m6mK-04/edit#
tcp throughput experiments with iperf3 
udp throughput experiments with trafgen/netsniff-ng
both for pod2pod same node, pod2pod different node, node2pod same node, node2pod different node

plus connectivity tests related to the use of services instead of ip addresses

_Originally posted by @StefanoSalsano in https://github.com/ferrarimarco/kubernetes-playground/pull/109_

**Comment by ferrarimarco** [comment]
Related to #72
