### ISSUE TITLE
Upgrade Vagrant to 2.2.7

### ISSUE THREAD

**Issue by ferrarimarco** [ferrarimarco/kubernetes-playground#133]
@StefanoSalsano @zvfvrv @simonezacca can you confirm you're running on Vagrant 2.2.7? So I'll update the CI build to use that version.

**Comment by StefanoSalsano** [comment]
on my windows "a carbone" I can confirm 2.2.7

**Comment by StefanoSalsano** [comment]
it is 2.2.7 also on the debian VM with libvirt that Simone and me are sharing
I do not know about Vagrant on Simone's mac

**Comment by zvfvrv** [comment]
yes 2.2.7
