### ISSUE TITLE
Move the Centos SSH configuration script out of the Vagrantfile

### ISSUE THREAD

**Issue by ferrarimarco** [ferrarimarco/kubernetes-playground#136]
We don't lint/check/test embedded scripts, so we should move the inline scripts that enables password authentication for SSH connections out of the Vagrantfile, so it can verified along with the other scripts.

**Comment by StefanoSalsano** [comment]
ahahah I've seen the new label "technical debt" nice and violet :-)

**Comment by ferrarimarco** [comment]
We deserved one :D
