### ISSUE TITLE
Don't install Docker Compose

### ISSUE THREAD

**Issue by ferrarimarco** [ferrarimarco/kubernetes-playground#137]
The docker role installs Docker and Docker Compose, because it was meant to be a general purpose role.

Now that's in this repository, we might avoid installing Docker Compose, because it takes a lot of time in the current implementation of the role (we blindly check if the binary we download is the same as the one we already have).

We don't need docker compose, so instead of spending time in refining how we install it, I propose we remove it entirely.

WDYT?

@StefanoSalsano @zvfvrv

**Comment by StefanoSalsano** [comment]
strong agreement !
