### ISSUE TITLE
No additional disks are created if using libvirt as a provider

### ISSUE THREAD

**Issue by ferrarimarco** [ferrarimarco/kubernetes-playground#153]
We only support the creation of additional disks when running on Virtualbox. For this reason, we cannot deploy GlusterFS when running on libvirt.

**Comment by StefanoSalsano** [comment]
we could add on the README.md in the Cloud Native Storage section that GlusterFS is only supported for the virtualbox provider

**Comment by ferrarimarco** [comment]
I'd like to keep the feature parity between providers when resonable. This sounds like a reasonably small change, because [vagrant-libvirt natively supports this](https://github.com/vagrant-libvirt/vagrant-libvirt#additional-disks).

@zvfvrv can you have a look at this?

**Comment by zvfvrv** [comment]
@ferrarimarco yes

**Comment by ferrarimarco** [comment]
Thanks!

Some useful pointers:

1. [GlusterFS topology](https://github.com/ferrarimarco/kubernetes-playground/blob/master/kubernetes/glusterfs/topology.json): it expects the second disk to be /dev/sdb, then it takes care of the rest.

Note that there's a shortcoming in that template (fixed IPs and device names). I'll open a new issue to track this, but for now don't worry.

Thanks!
