### ISSUE TITLE
Add an echo to show which provider is currently configured

### ISSUE THREAD

**Issue by ferrarimarco** [ferrarimarco/kubernetes-playground#157]
Having a line in the log saying which provider is currently configured might help debug issues.

We might even extend this to write the full configuration.

**Comment by StefanoSalsano** [comment]
it was my mistake... so I closed issue #156 ... anyway a single line printout with the configured provider and the configured plugin, after the line about vagrant version would be helpful... I can add this feature to the PR I am working in!

**Comment by ferrarimarco** [comment]
Great, thanks! I'll add a reminder in that one then :)
