### ISSUE TITLE
support easy debbuging of ansible tasks in kubernetes.yml with a dedicated vagrant provisioner

### ISSUE THREAD

**Issue by StefanoSalsano** [ferrarimarco/kubernetes-playground#158]
I've created a --provision-with ansible-debug-tag in Vagrantfile
this provisioner allows calling ansible with --tags ansible_debug so that we can easily add debug tasks that are the only ones that will be called
(in this respect, we should also merge kubernetes.yml and openssl-self-signed-certificate.yml)
I've added an example task in kubernetes.yml

**Comment by ferrarimarco** [comment]
Closed by #147
