### ISSUE TITLE
merging kubernetes.yml and openssl-self-signed-certificate.yml

### ISSUE THREAD

**Issue by StefanoSalsano** [ferrarimarco/kubernetes-playground#163]
currently we cannot control the tasks in openssl-self-signed-certificate.yml with tags

can we move everything into kubernetes.yml ?

**Comment by ferrarimarco** [comment]
Why we can't? We pass `$additional_ansible_arguments` to both Ansible instances (and after #164 there will be only one instance running). So the only thing to do would be to tag tasks in `openssl-self-signed-certificate.yml` with the `quick_setup` tag if you want to run them during quick setup.

Isn't this the case?

**Comment by StefanoSalsano** [comment]
ok you are right, sorry!!... I was reading too much information also in quick-setup and I thought we should still fix it... but we fixed it a while ago adding the tags to ansible invocation

no I do not want to add more tasks to quick-setup ;-)
