### ISSUE TITLE
The initialization of the Kubernetes master fails to find /etc/kubernetes/admin.conf

### ISSUE THREAD

**Issue by simonezacca** [ferrarimarco/kubernetes-playground#17]
Hi Marco,

I downloaded the repository and tried to install everything with the "vagrant up" command. The first time my computer got freeze, probably because of only 8GB of RAM. 

[vagrantup.log](https://github.com/ferrarimarco/kubernetes-playground/files/3993204/vagrantup.log)

After a forced reboot, i tried again initially using "vagrant up" and then "vagrant provision" as suggested by Vagrant. 

[vagrantup2.log](https://github.com/ferrarimarco/kubernetes-playground/files/3993207/vagrantup2.log)

[vagrantprovision.log](https://github.com/ferrarimarco/kubernetes-playground/files/3993211/vagrantprovision.log)

I think the problem is here, in fact, later, if i try to inizialize Helm tells me:

> MacBook-Pro-di-Simone:kubernetes-playground-master simone$ vagrant ssh kubernetes-master-1.kubernetes-playground.local
Last login: Mon Dec 23 00:19:31 2019 from 10.0.2.2
[vagrant@kubernetes-master-1 ~]$ sudo /vagrant/scripts/linux/bootstrap-helm.sh
The connection to the server localhost:8080 was refused - did you specify the right host or port?

As if there had been some problem in the configuration. I have tried this solution:
https://github.com/kubernetes/kubernetes/issues/44665#issuecomment-295216655

This is the answer:

> [vagrant@kubernetes-master-1 ~]$ kubeadm init
W1223 00:55:17.177615    7187 validation.go:28] Cannot validate kube-proxy config - no validator is available
W1223 00:55:17.177694    7187 validation.go:28] Cannot validate kubelet config - no validator is available
[init] Using Kubernetes version: v1.17.0
[preflight] Running pre-flight checks
error execution phase preflight: [preflight] Some fatal errors occurred:
	[ERROR IsPrivilegedUser]: user is not running as root
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher

I will try to install this repository on another computer, i'll let you know if i have the same problem!

**Comment by ferrarimarco** [comment]
The various Ansible roles and playbooks take care of the steps mentioned in https://github.com/kubernetes/kubernetes/issues/44665#issuecomment-295216655, so there should be no need for doing that.

It looks like Kubernetes is not actually running, that's why you cannot connect to the cluster.

I see from your logs that the initialization has not been completed. For everything to work, the Ansible playbooks and the rest of the provisioning and configuration scripts must run without errors.

Can you please:

1. Run `vagrant destroy`
1. Run `vagrant up` once again
1. Post the output here

**Comment by simonezacca** [comment]
I confirm that the problem is my computer, in fact, continues to freeze at the same time (during the initialization of Ansible), not allowing the correct installation.

I will also try on the other computer, which also contains 8 GB of RAM.

Thanks anyway for the support and happy Holidays!

**Comment by ferrarimarco** [comment]
Can you:

1. ssh in the k8s master
1. Post the contents of `/tmp/kubeadm-config.yaml`
1. Post the listing of the `/etc/kubernetes` directory

**Comment by ferrarimarco** [comment]
Relevant output

```
    ansible-controller.kubernetes-playground.local: TASK [Initialize Kubernetes cluster (master)] **********************************
    ansible-controller.kubernetes-playground.local: fatal: [192.168.2.10]: FAILED! => {"changed": true, "cmd": "/vagrant/scripts/linux/bootstrap-kubernetes-master.sh /tmp/kubeadm-config.yaml weavenet", "delta": "0:00:01.077072", "end": "2019-12-23 00:18:14.860749", "msg": "non-zero return code", "rc": 1, "start": "2019-12-23 00:18:13.783677", "stderr": "W1223 00:18:14.470089    6985 validation.go:28] Cannot validate kube-proxy config - no validator is available\nW1223 00:18:14.470152    6985 validation.go:28] Cannot validate kubelet config - no validator is available\n\t[WARNING IsDockerSystemdCheck]: detected \"cgroupfs\" as the Docker cgroup driver. The recommended driver is \"systemd\". Please follow the guide at https://kubernetes.io/docs/setup/cri/\nerror execution phase preflight: [preflight] Some fatal errors occurred:\n\t[ERROR KubeletVersion]: couldn't get kubelet version: cannot execute 'kubelet --version': signal: segmentation fault\n[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`\nTo see the stack trace of this error execute with --v=5 or higher\ncp: cannot stat ‘/etc/kubernetes/admin.conf’: No such file or directory\nchown: cannot access ‘/root/.kube/config’: No such file or directory\ncp: cannot stat ‘/etc/kubernetes/admin.conf’: No such file or directory\nchown: cannot access ‘/home/vagrant/.kube/config’: No such file or directory\nThe connection to the server localhost:8080 was refused - did you specify the right host or port?\nThe connection to the server localhost:8080 was refused - did you specify the right host or port?", "stderr_lines": ["W1223 00:18:14.470089    6985 validation.go:28] Cannot validate kube-proxy config - no validator is available", "W1223 00:18:14.470152    6985 validation.go:28] Cannot validate kubelet config - no validator is available", "\t[WARNING IsDockerSystemdCheck]: detected \"cgroupfs\" as the Docker cgroup driver. The recommended driver is \"systemd\". Please follow the guide at https://kubernetes.io/docs/setup/cri/", "error execution phase preflight: [preflight] Some fatal errors occurred:", "\t[ERROR KubeletVersion]: couldn't get kubelet version: cannot execute 'kubelet --version': signal: segmentation fault", "[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`", "To see the stack trace of this error execute with --v=5 or higher", "cp: cannot stat ‘/etc/kubernetes/admin.conf’: No such file or directory", "chown: cannot access ‘/root/.kube/config’: No such file or directory", "cp: cannot stat ‘/etc/kubernetes/admin.conf’: No such file or directory", "chown: cannot access ‘/home/vagrant/.kube/config’: No such file or directory", "The connection to the server localhost:8080 was refused - did you specify the right host or port?", "The connection to the server localhost:8080 was refused - did you specify the right host or port?"], "stdout": "Initializing Kubernetes master with configuration file: /tmp/kubeadm-config.yaml. Contents: apiVersion: kubeadm.k8s.io/v1beta2\nbootstrapTokens:\n- groups:\n  token: \"0y5van.5qxccw2ewiarl68v\"\nkind: InitConfiguration\nlocalAPIEndpoint:\n  advertiseAddress: \"192.168.2.10\"\n---\napiVersion: kubeadm.k8s.io/v1beta2\nkind: ClusterConfiguration\napiServer:\n  extraArgs:\n    service-node-port-range: \"80-32767\"\n[init] Using Kubernetes version: v1.17.0\n[preflight] Running pre-flight checks\nInstalling weavenet network plugin", "stdout_lines": ["Initializing Kubernetes master with configuration file: /tmp/kubeadm-config.yaml. Contents: apiVersion: kubeadm.k8s.io/v1beta2", "bootstrapTokens:", "- groups:", "  token: \"0y5van.5qxccw2ewiarl68v\"", "kind: InitConfiguration", "localAPIEndpoint:", "  advertiseAddress: \"192.168.2.10\"", "---", "apiVersion: kubeadm.k8s.io/v1beta2", "kind: ClusterConfiguration", "apiServer:", "  extraArgs:", "    service-node-port-range: \"80-32767\"", "[init] Using Kubernetes version: v1.17.0", "[preflight] Running pre-flight checks", "Installing weavenet network plugin"]}
    ansible-controller.kubernetes-playground.local:     to retry, use: --limit @/etc/ansible/playbooks/kubernetes.retry
```

**Comment by simonezacca** [comment]
> Can you:
> 
> 1. ssh in the k8s master
> 2. Post the contents of `/tmp/kubeadm-config.yaml`
> 3. Post the listing of the `/etc/kubernetes` directory

I tried again to do **vagrant destroy** and then **vagrant up**. My computer always crashes at this point not allowing correct installation and forcing me to forcefully restart the PC:

> ansible-controller.kubernetes-playground.local: TASK [ferrarimarco.kubernetes : Install Kubernetes packages] *******************
>     ansible-controller.kubernetes-playground.local: changed: [192.168.2.10] => (item=conntrack-tools)
>     ansible-controller.kubernetes-playground.local: changed: [192.168.2.31] => (item=conntrack-tools)
>     ansible-controller.kubernetes-playground.local: changed: [192.168.2.32] => (item=conntrack-tools)
>     ansible-controller.kubernetes-playground.local: changed: [192.168.2.30] => (item=conntrack-tools)
> 
>   [Ripristinato: 26 dic 2019, 14:07:17]
> Last login: Thu Dec 26 14:07:06 on console
> MacBook-Pro-di-Simone:kubernetes-playground-master simone$

If i enter in K8s Master:
2. i don't have folder /tmp
3. Have only manifests file in /etc/kubernetes directory

But the main problem I think is the incorrect initialization of Ansible during the vagrant up command since it always crashes at that point (obviously during the installation I leave open only the terminal).

**Comment by simonezacca** [comment]
This is the complete log of vagrant destroy and vagrant up:

[vagrantdestroyvagrantup.log](https://github.com/ferrarimarco/kubernetes-playground/files/4002672/vagrantdestroyvagrantup.log)

**Comment by ahmedgdoma** [comment]
> For example, if you are intending to run a Kubernetes cluster on your laptop (locally), you will need a tool like Minikube to be installed first and then re-run the commands stated above.

https://kubernetes.io/docs/tasks/tools/install-kubectl/#verifying-kubectl-configuration

**Comment by ferrarimarco** [comment]
@simonezacca the last log seems not complete

**Comment by simonezacca** [comment]
> This is the complete log of vagrant destroy and vagrant up:
> 
> [vagrantdestroyvagrantup.log](https://github.com/ferrarimarco/kubernetes-playground/files/4002672/vagrantdestroyvagrantup.log)

Hi Marco,
Sorry for the delay, unfortunately I can not see them at that exact moment because the PC freeze and the only thing I can do is restart it forcedly. 

Through a Widget (iStat Menus) that I have on the menu bar, at the time of the freeze, the bars that concern RAM and CPU are practically at the maximum. So I believe that all the resources are in that moment dedicated to Vagrant and the initialization of the environment.

In the last log I sent you (in response), there is the whole procedure of "Vagrant right" and "Vagrant up" until the moment of freezing. I was able to recover this registry after forcibly restarting the PC.

Thanks in advance for the support as always! 👍

**Comment by ferrarimarco** [comment]
I guess you may try lowering the allocated resources in the Vagrantfile (start with lowering the reserved RAM).

If that works, we might benchmark a bit to see if a lower amount of RAM is enough.

**Comment by simonezacca** [comment]
I set the following RAM resources:

Kubernetes Master: 2048MB
Kubernetes Minion-1: 1024MB
Kubernetes Minion-2: 1024MB
Kubernetes Minion-3: 1024MB
Ansible: 512MB

Now the computer does not crash, but during initialization it gives me an error for which i can't find a solution (at the end of the logs), do you have any idea?

This is the new "vagrant up" log:

[VagrantUp.log](https://github.com/ferrarimarco/kubernetes-playground/files/4037235/VagrantUp.log)

I got the debug level output (recommend seeing the end of the logs directly) using:

`vagrant up --debug &> debug.log`

[debug.log](https://github.com/ferrarimarco/kubernetes-playground/files/4037236/debug.log)

**Comment by ferrarimarco** [comment]
I guess this is just a temporary error. From your `vagrant up` log:

```
[Errno 14] curl#18 - \"transfer closed with 6481570 bytes remaining to read\"\nTrying other mirror.\n\n\nError downloading packages:\n  kubelet-1.17.0-0.x86_64: [Errno 256] No more mirrors to try.
```

**Comment by ferrarimarco** [comment]
And actually that's another issue. Closing this one in favor of #9 

Please open a new issue if the error persists, so we can better track progress

**Comment by manishalankala** [comment]
i also don't find admin.conf in the location

my kubelet service not recognized

how can can i fix this

**Comment by ferrarimarco** [comment]
Hi @manishalankala . Can you please open a new issue and attach logs that show the problem? Thanks
