### ISSUE TITLE
stop ansible kubernetes.yml whe the initialization of the kubernetes master fails

### ISSUE THREAD

**Issue by StefanoSalsano** [ferrarimarco/kubernetes-playground#188]
TASK [Initialize Kubernetes cluster (master)] **********************************
task path: /etc/ansible/kubernetes.yml:175

if this task fails, we should stop...
instead it continues trying to initialize the minions and it stops after a VERY long timeout

**Comment by ferrarimarco** [comment]
Right!

**Comment by ferrarimarco** [comment]
We might enable it for the whole play: https://docs.ansible.com/ansible/latest/user_guide/playbooks_error_handling.html#aborting-the-play

I think it's fair in our case, because currently the vast majority of our tasks are non-optional.

**Comment by StefanoSalsano** [comment]
ok I agree, I've already implemented the solution only for the task of kubernetes master configuration, I'm now checking how to do for the whole play and then I'll submit a PR
