### ISSUE TITLE
migrate to kubernetes 1.18

### ISSUE THREAD

**Issue by StefanoSalsano** [ferrarimarco/kubernetes-playground#189]
v1.18.0 has been released on 25 March 2020

https://kubernetes.io/docs/setup/release/notes/#changelog-since-v1-17-0

**Comment by ferrarimarco** [comment]
We don't specify a Kubernetes version, so as long as packages are published in the OS package manager repo of choice, to have the latest version of K8S you just reprovision the base-box.

There's an area of improvement tho: set the k8s version in defaults.yaml, so the environment is reproducible?
