### ISSUE TITLE
Vagrant Up may get locked on "Pruning invalid NFS exports"

### ISSUE THREAD

**Issue by simonezacca** [ferrarimarco/kubernetes-playground#196]
Hi Marco!

I noticed that the vagrant up may get locked on this:

`Pruning invalid NFS exports. Administrator privileges will be required ...`

Continue the procedure only after entering manually the password.

**Comment by simonezacca** [comment]
![Example](https://user-images.githubusercontent.com/16154904/80411654-d5ce6280-88cc-11ea-8f0a-6ad4256ef49d.JPG)

**Comment by zvfvrv** [comment]
Hi @simonezacca,
maybe this can help  https://www.vagrantup.com/docs/synced-folders/nfs.html#root-privilege-requirement

**Comment by simonezacca** [comment]
> Hi @simonezacca,
> maybe this can help https://www.vagrantup.com/docs/synced-folders/nfs.html#root-privilege-requirement
It works! @zvfvrv 
Thank you :D
