### ISSUE TITLE
Ansible cannot execute the initialization script (permission denied)

### ISSUE THREAD

**Issue by plungaroni** [ferrarimarco/kubernetes-playground#20]
Abbiamo eseguito in due ambienti diversi il vagrant up ed in entrambi abbiamo avuto un errore su gli ansible scripts per l'inizializzazione del cluster (sia il master che i workers): 
ansible-controller.kubernetes-playground.local: TASK [Initialize Kubernetes cluster (master)]

```
ansible-controller.kubernetes-playground.local: fatal: [192.168.0.10]: FAILED! => {"changed": true, "cmd": "/vagrant/scripts/linux/bootstrap-kubernetes-master.sh /tmp/kubeadm-config.yaml calico", "delta": "0:00:00.008279", "end": "2020-01-09 17:23:40.784003", "msg": "non-zero return code", "rc": 126, "start": "2020-01-09 17:23:40.775724", "stderr": "/bin/sh: /vagrant/scripts/linux/bootstrap-kubernetes-master.sh: Permission denied", "stderr_lines": ["/bin/sh: /vagrant/scripts/linux/bootstrap-kubernetes-master.sh: Permission denied"], "stdout": "", "stdout_lines": []}
```

Il dettaglio con il log completo:
[vagrant-overall.log](https://github.com/ferrarimarco/kubernetes-playground/files/4041684/vagrant-overall.log)

**Comment by ferrarimarco** [comment]
Hi!

Can you please open a ssh session and run `ls -al /vagrant/scripts/linux/` on any of the machines?

Which host systems are you currently using?

**Comment by StefanoSalsano** [comment]
ciao Marco may be we have understood: the .sh files are not executable
when we clone the repository, they are not executable and so they are seen as not executable in the /vagrant/... folders both in the master and in the minions

**Comment by StefanoSalsano** [comment]
we are using linux host

**Comment by ferrarimarco** [comment]
Let me check. I would understand the error if you were running on a Windows host, because it does not preserve the executable bit.

They have the executable bit set to 1 on my setup...

Can you:

1. Run `ls -al in scripts/linux` on the host
1. Open a ssh session and run `ls -al /vagrant/scripts/linux/` on any of the machines (master or workers)

Thanks!

**Comment by StefanoSalsano** [comment]
may be your host is not aligned with github repo for some reason?
if I run
git clone https://github.com/ferrarimarco/kubernetes-playground
and then
ls -la kubernetes-playground/scripts/linux/
all the scripts are not executable (but one)
drwxrwxr-x 2 user user 4096 gen  9 22:25 .
drwxrwxr-x 3 user user 4096 gen  9 22:25 ..
-rw-rw-r-- 1 user user  400 gen  9 22:25 bootstrap-docker-registry.sh
-rw-rw-r-- 1 user user  585 gen  9 22:25 bootstrap-glusterfs.sh
-rw-rw-r-- 1 user user  571 gen  9 22:25 bootstrap-helm.sh
-rw-rw-r-- 1 user user  221 gen  9 22:25 bootstrap-ingress-controller.sh
-rw-rw-r-- 1 user user  946 gen  9 22:25 bootstrap-kubernetes-master.sh
-rw-rw-r-- 1 user user  435 gen  9 22:25 bootstrap-kubernetes-minion.sh
-rw-rw-r-- 1 user user  285 gen  9 22:25 bootstrap-monitoring.sh
-rw-rw-r-- 1 user user  256 gen  9 22:25 check-kubeadm-requirements.sh
-rw-rw-r-- 1 user user  435 gen  9 22:25 install-docker.sh
-rw-rw-r-- 1 user user  402 gen  9 22:25 install-kubernetes.sh
-rwxrwxr-x 1 user user  680 gen  9 22:25 setup-debian.sh

**Comment by ferrarimarco** [comment]
Thanks @StefanoSalsano I'll doublecheck

**Comment by ferrarimarco** [comment]
Anyway, to avoid this in the future, I'll add a check in the CI build and as "pre-flight" checks that run automatically on `vagrant up`.

**Comment by StefanoSalsano** [comment]
In the windows host, the +x is added automatically to all files in the shared folders seen by the guests, so there is no problem
Considering that the linux host preserves the file permissions we could add an ansible task that adds +× to all scripts... so we will be on the safe side

Il 9 Gennaio 2020 22:50:45 CET, Marco Ferrari <notifications@github.com> ha scritto:
>Anyway, to avoid this in the future, I'll add a check in the CI build
>and as "pre-flight" checks that run automatically on `vagrant up`.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/ferrarimarco/kubernetes-playground/issues/20#issuecomment-572772716

-- 
Inviato dal mio dispositivo Android con K-9 Mail. Perdonate la brevità.

**Comment by ferrarimarco** [comment]
This could not cover scripts that are not executed by ansible. :(
