### ISSUE TITLE
support the needs of SRv6-PM project

### ISSUE THREAD

**Issue by StefanoSalsano** [ferrarimarco/kubernetes-playground#204]
this is an umbrella issue, covering several sub issues

the overall scenario of the SRv6 PM project is to have two hosts on which we want to distribute a kubernetes workload made up of several containers: kafka, everySMART (a python SDN controller), influxDB, arangoDB, grafana, ...

**Comment by ferrarimarco** [comment]
Closing this, because we already have all the issues we need to track what we need.
