### ISSUE TITLE
The environment customization doesn't support partial overrides

### ISSUE THREAD

**Issue by ferrarimarco** [ferrarimarco/kubernetes-playground#21]
When overriding the default configuration with an `env.yaml` file, we currently have to specify all the subkeys of a key, unless we want them to be lost in the merge.

**Comment by StefanoSalsano** [comment]
@ferrarimarco where is implemented the logic for the merging of defaults.yaml and env.yaml ?
is it only a problem of implementing a more complex logic for the merging?

**Comment by ferrarimarco** [comment]
The logic is in the [Vagrantfile](https://github.com/ferrarimarco/kubernetes-playground/blob/master/Vagrantfile#L12)
