### ISSUE TITLE
vagrant up with libvirt doesn't work after switching to a Debian environment

### ISSUE THREAD

**Issue by simonezacca** [ferrarimarco/kubernetes-playground#242]
When i switched to the Debian environment, i encountered an error while provisioning the machines.
To be more precise, after doing the whole "_How to Run_" procedure, after creating and exporting the box, i have the following error to the _vagrant up_ step.
In this example only for the master, but it also happens with workers:

- Vagrant Version: 2.2.9
- Vagrant Provider: libvirt

> cnis@cloud:~/kubernetes-playground$ vagrant up k8s-master-1.k8s-play.local
Welcome to Kubernetes playground!
Vagrant provider: libvirt
Networking plugin: weavenet
Bringing machine 'k8s-master-1.k8s-play.local' up with 'libvirt' provider...
==> k8s-master-1.k8s-play.local: Creating image (snapshot of base box volume).
==> k8s-master-1.k8s-play.local: Creating domain with the following settings...
==> k8s-master-1.k8s-play.local:  -- Name:              k8s-master-1.k8s-play.local
==> k8s-master-1.k8s-play.local:  -- Domain type:       kvm
==> k8s-master-1.k8s-play.local:  -- Cpus:              2
==> k8s-master-1.k8s-play.local:  -- Feature:           acpi
==> k8s-master-1.k8s-play.local:  -- Feature:           apic
==> k8s-master-1.k8s-play.local:  -- Feature:           pae
==> k8s-master-1.k8s-play.local:  -- Memory:            2048M
==> k8s-master-1.k8s-play.local:  -- Management MAC:    
==> k8s-master-1.k8s-play.local:  -- Loader:            
==> k8s-master-1.k8s-play.local:  -- Nvram:             
==> k8s-master-1.k8s-play.local:  -- Base box:          ferrarimarco/kubernetes-playground-node
==> k8s-master-1.k8s-play.local:  -- Storage pool:      default
==> k8s-master-1.k8s-play.local:  -- Image:             /var/lib/libvirt/images/k8s-master-1.k8s-play.local.img (20G)
==> k8s-master-1.k8s-play.local:  -- Volume Cache:      default
==> k8s-master-1.k8s-play.local:  -- Kernel:            
==> k8s-master-1.k8s-play.local:  -- Initrd:            
==> k8s-master-1.k8s-play.local:  -- Graphics Type:     vnc
==> k8s-master-1.k8s-play.local:  -- Graphics Port:     -1
==> k8s-master-1.k8s-play.local:  -- Graphics IP:       127.0.0.1
==> k8s-master-1.k8s-play.local:  -- Graphics Password: Not defined
==> k8s-master-1.k8s-play.local:  -- Video Type:        cirrus
==> k8s-master-1.k8s-play.local:  -- Video VRAM:        9216
==> k8s-master-1.k8s-play.local:  -- Sound Type:	
==> k8s-master-1.k8s-play.local:  -- Keymap:            en-us
==> k8s-master-1.k8s-play.local:  -- TPM Path:          
==> k8s-master-1.k8s-play.local:  -- Disks:         sdb(qcow2,10240)
==> k8s-master-1.k8s-play.local:  -- Disk(sdb):     /var/lib/libvirt/images/k8s-master-1.k8s-play.local_sdb.img
==> k8s-master-1.k8s-play.local:  -- INPUT:             type=mouse, bus=ps2
==> k8s-master-1.k8s-play.local: Creating shared folders metadata...
==> k8s-master-1.k8s-play.local: Starting domain.
==> k8s-master-1.k8s-play.local: Waiting for domain to get an IP address...
==> k8s-master-1.k8s-play.local: Removing domain...
Traceback (most recent call last):
	67: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/batch_action.rb:86:in `block (2 levels) in run'
	66: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/machine.rb:198:in `action'
	65: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/machine.rb:198:in `call'
	64: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/environment.rb:613:in `lock'
	63: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/machine.rb:212:in `block in action'
	62: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/machine.rb:240:in `action_raw'
	61: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/runner.rb:89:in `run'
	60: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/util/busy.rb:19:in `busy'
	59: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/runner.rb:89:in `block in run'
	58: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/builder.rb:116:in `call'
	57: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/warden.rb:48:in `call'
	56: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	55: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/warden.rb:48:in `call'
	54: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/builtin/box_check_outdated.rb:36:in `call'
	53: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/warden.rb:48:in `call'
	52: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/builtin/call.rb:53:in `call'
	51: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/runner.rb:89:in `run'
	50: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/util/busy.rb:19:in `busy'
	49: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/runner.rb:89:in `block in run'
	48: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/builder.rb:116:in `call'
	47: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/warden.rb:48:in `call'
	46: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/warden.rb:107:in `block in finalize_action'
	45: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/warden.rb:48:in `call'
	44: from /home/cnis/.vagrant.d/gems/2.6.6/gems/vagrant-libvirt-0.1.2/lib/vagrant-libvirt/action/set_name_of_domain.rb:32:in `call'
	43: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/warden.rb:48:in `call'
	42: from /home/cnis/.vagrant.d/gems/2.6.6/gems/vagrant-libvirt-0.1.2/lib/vagrant-libvirt/action/handle_storage_pool.rb:57:in `call'
	41: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/warden.rb:48:in `call'
	40: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
	39: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/warden.rb:48:in `call'
	38: from /home/cnis/.vagrant.d/gems/2.6.6/gems/vagrant-libvirt-0.1.2/lib/vagrant-libvirt/action/handle_box_image.rb:124:in `call'
	37: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/warden.rb:48:in `call'
	36: from /home/cnis/.vagrant.d/gems/2.6.6/gems/vagrant-libvirt-0.1.2/lib/vagrant-libvirt/action/create_domain_volume.rb:89:in `call'
	35: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/warden.rb:48:in `call'
	34: from /home/cnis/.vagrant.d/gems/2.6.6/gems/vagrant-libvirt-0.1.2/lib/vagrant-libvirt/action/create_domain.rb:363:in `call'
	33: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/warden.rb:48:in `call'
	32: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/builtin/provision.rb:80:in `call'
	31: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/warden.rb:48:in `call'
	30: from /home/cnis/.vagrant.d/gems/2.6.6/gems/vagrant-libvirt-0.1.2/lib/vagrant-libvirt/action/prepare_nfs_valid_ids.rb:12:in `call'
	29: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/warden.rb:48:in `call'
	28: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/plugins/synced_folders/nfs/action_cleanup.rb:25:in `call'
	27: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/warden.rb:48:in `call'
	26: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/builtin/synced_folder_cleanup.rb:28:in `call'
	25: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/warden.rb:48:in `call'
	24: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/builtin/delayed.rb:19:in `call'
	23: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/warden.rb:48:in `call'
	22: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/builtin/synced_folders.rb:87:in `call'
	21: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/warden.rb:48:in `call'
	20: from /home/cnis/.vagrant.d/gems/2.6.6/gems/vagrant-libvirt-0.1.2/lib/vagrant-libvirt/action/prepare_nfs_settings.rb:19:in `call'
	19: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/warden.rb:48:in `call'
	18: from /home/cnis/.vagrant.d/gems/2.6.6/gems/vagrant-libvirt-0.1.2/lib/vagrant-libvirt/action/share_folders.rb:20:in `call'
	17: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/warden.rb:48:in `call'
	16: from /home/cnis/.vagrant.d/gems/2.6.6/gems/vagrant-libvirt-0.1.2/lib/vagrant-libvirt/action/create_networks.rb:89:in `call'
	15: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/warden.rb:48:in `call'
	14: from /home/cnis/.vagrant.d/gems/2.6.6/gems/vagrant-libvirt-0.1.2/lib/vagrant-libvirt/action/create_network_interfaces.rb:184:in `call'
	13: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/warden.rb:48:in `call'
	12: from /home/cnis/.vagrant.d/gems/2.6.6/gems/vagrant-libvirt-0.1.2/lib/vagrant-libvirt/action/set_boot_order.rb:78:in `call'
	11: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/warden.rb:48:in `call'
	10: from /home/cnis/.vagrant.d/gems/2.6.6/gems/vagrant-libvirt-0.1.2/lib/vagrant-libvirt/action/start_domain.rb:302:in `call'
	 9: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/warden.rb:48:in `call'
	 8: from /home/cnis/.vagrant.d/gems/2.6.6/gems/vagrant-libvirt-0.1.2/lib/vagrant-libvirt/action/wait_till_up.rb:51:in `call'
	 7: from /home/cnis/.vagrant.d/gems/2.6.6/gems/vagrant-libvirt-0.1.2/lib/vagrant-libvirt/util/timer.rb:9:in `time'
	 6: from /home/cnis/.vagrant.d/gems/2.6.6/gems/vagrant-libvirt-0.1.2/lib/vagrant-libvirt/action/wait_till_up.rb:52:in `block in call'
	 5: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/util/retryable.rb:17:in `retryable'
	 4: from /home/cnis/.vagrant.d/gems/2.6.6/gems/vagrant-libvirt-0.1.2/lib/vagrant-libvirt/action/wait_till_up.rb:57:in `block (2 levels) in call'
	 3: from /home/cnis/.vagrant.d/gems/2.6.6/gems/fog-core-2.2.0/lib/fog/core/model.rb:72:in `wait_for'
	 2: from /home/cnis/.vagrant.d/gems/2.6.6/gems/fog-core-2.2.0/lib/fog/core/wait_for.rb:6:in `wait_for'
	 1: from /home/cnis/.vagrant.d/gems/2.6.6/gems/fog-core-2.2.0/lib/fog/core/wait_for.rb:6:in `loop'
/home/cnis/.vagrant.d/gems/2.6.6/gems/fog-core-2.2.0/lib/fog/core/wait_for.rb:9:in `block in wait_for': The specified wait_for timeout (2 seconds) was exceeded (Fog::Errors::TimeoutError)

**Comment by ferrarimarco** [comment]
After some investigation, we realized that the master-1 (or any other cluster VM), never gets an IP address because it cannot boot.

@simonezacca can you add the relevant screenshot?

**Comment by simonezacca** [comment]
During provisioning, I can see the VM details from Virtual Machine Manager, and trying to access the machine I encounter this problem:
![master1](https://user-images.githubusercontent.com/16154904/82669893-8285d080-9c3c-11ea-84b7-ff9af1719f74.png)

**Comment by ferrarimarco** [comment]
This looks like a possible cause. The VM is not getting an IP because it cannot boot. Fair :)

Let's dig a bit deeper.

**Comment by ferrarimarco** [comment]
We opened a shell connecting to the VM serial console to investigate, but we had keyboard layout issues. After forcefully rebooting the VM, it finally picked the correct layout.

**Comment by simonezacca** [comment]
> We opened a shell connecting to the VM serial console to investigate, but we had keyboard layout issues. After forcefully rebooting the VM, it finally picked the correct layout.

The US layout appears after setting the IT layout in "VNC display", forced shutdown and started again. Very strange, but working.

**Comment by simonezacca** [comment]
![ls-master-vmm-6](https://user-images.githubusercontent.com/16154904/82674476-a7317680-9c43-11ea-9a1f-c11c437cd72f.PNG)

**Comment by simonezacca** [comment]
We also checked the contents of the box.img
![file-img](https://user-images.githubusercontent.com/16154904/82698085-74e73f80-9c6a-11ea-9c59-5e0c5152dc88.PNG)
![file-img2](https://user-images.githubusercontent.com/16154904/82698084-744ea900-9c6a-11ea-9848-5a4efbadd38f.PNG)

**Comment by ferrarimarco** [comment]
After some more debugging, we found out that the GRUB configuration file (grub.cfg) that is packed in the base box [is not the same](http://www.mergely.com/8T0Fkc0T/) one that the master-1 (and other VMs) use to boot.

**Comment by ferrarimarco** [comment]
When running the base box, it uses a GRUB config file for Debian, while the other VMs use a config file for Ubuntu!

**Comment by ferrarimarco** [comment]
We're currently investigating on why this happens.

**Comment by simonezacca** [comment]
/boot/grub/grub.cfg in base_box.img

[grub_basebox.txt](https://github.com/ferrarimarco/kubernetes-playground/files/4673706/grub_basebox.txt)

**Comment by simonezacca** [comment]
Error/Warning in _/var/log/syslog_
![syslog1](https://user-images.githubusercontent.com/16154904/82809187-cb7f9400-9e8b-11ea-9ac3-78d2d507ad4e.PNG)
![syslog2](https://user-images.githubusercontent.com/16154904/82809188-cb7f9400-9e8b-11ea-92ed-6326de1a0edd.PNG)
![syslog3](https://user-images.githubusercontent.com/16154904/82809189-cc182a80-9e8b-11ea-958a-928d57dd6a63.PNG)
![syslog4](https://user-images.githubusercontent.com/16154904/82809190-cc182a80-9e8b-11ea-9a64-39ef0946f9df.PNG)
![syslog5](https://user-images.githubusercontent.com/16154904/82809185-cae6fd80-9e8b-11ea-83e6-40589da24405.PNG)

**Comment by ferrarimarco** [comment]
1. AUFS message. We should switch to [overlay2](https://docs.docker.com/storage/storagedriver/overlayfs-driver/).

2. No such file or directory by systemd: let's see if we have all the needed modules.

3. SSH keys: let's check the SSH configuration

**Comment by ferrarimarco** [comment]
The DHCP client is not able to obtain a lease.

Possible symptoms:

- From syslog: `Failed to set IAID+DUID: No such file or directory`
- From diagnostics:

```
-------- START virsh (virsh net-dhcp-leases vagrant-libvirt), pwd: /home/travis/build/ferrarimarco/kubernetes-playground --------
 Expiry Time          MAC address        Protocol  IP address                Hostname        Client ID or DUID
-------------------------------------------------------------------------------------------------------------------
 2020-05-31 19:18:37  52:54:00:a3:83:a4  ipv4      192.168.121.17/24         base-box-builder ff:ed:10:bd:b8:00:02:00:00:ab:11:af:45:5e:d1:23:89:4f:01
-------- END virsh (virsh net-dhcp-leases vagrant-libvirt), pwd: /home/travis/build/ferrarimarco/kubernetes-playground --------
```

**Comment by ferrarimarco** [comment]
Update: I fixed the warning about AUFS by configuring Docker to use overlay2.
