### ISSUE TITLE
vagrant up fails with "Initialization parameters must be an attributes hash, got NilClass nil"

### ISSUE THREAD

**Issue by simonezacca** [ferrarimarco/kubernetes-playground#243]
- Vagrant Version: 2.2.9
- Vagrant Provider: libvirt

The error can occur during the vagrant up:

> ubuntu@k8s-server:~/kubernetes-playground$ vagrant up k8s-master-1.k8s-play.local
> Welcome to Kubernetes playground!
> Vagrant provider: libvirt
> Networking plugin: weavenet
> Bringing machine 'k8s-master-1.k8s-play.local' up with 'libvirt' provider...
> Traceback (most recent call last):
> 	36: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/batch_action.rb:86:in `block (2 levels) in run'
> 	35: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/machine.rb:198:in `action'
> 	34: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/machine.rb:198:in `call'
> 	33: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/environment.rb:613:in `lock'
> 	32: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/machine.rb:212:in `block in action'
> 	31: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/machine.rb:240:in `action_raw'
> 	30: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/runner.rb:89:in `run'
> 	29: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/util/busy.rb:19:in `busy'
> 	28: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/runner.rb:89:in `block in run'
> 	27: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/builder.rb:116:in `call'
> 	26: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/warden.rb:48:in `call'
> 	25: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
> 	24: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/warden.rb:48:in `call'
> 	23: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/builtin/box_check_outdated.rb:36:in `call'
> 	22: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/warden.rb:48:in `call'
> 	21: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/builtin/call.rb:53:in `call'
> 	20: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/runner.rb:89:in `run'
> 	19: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/util/busy.rb:19:in `busy'
> 	18: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/runner.rb:89:in `block in run'
> 	17: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/builder.rb:116:in `call'
> 	16: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/warden.rb:48:in `call'
> 	15: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/warden.rb:107:in `block in finalize_action'
> 	14: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/warden.rb:48:in `call'
> 	13: from /home/ubuntu/.vagrant.d/gems/2.6.6/gems/vagrant-libvirt-0.1.2/lib/vagrant-libvirt/action/set_name_of_domain.rb:32:in `call'
> 	12: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/warden.rb:48:in `call'
> 	11: from /home/ubuntu/.vagrant.d/gems/2.6.6/gems/vagrant-libvirt-0.1.2/lib/vagrant-libvirt/action/handle_storage_pool.rb:57:in `call'
> 	10: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/warden.rb:48:in `call'
> 	 9: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
> 	 8: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/warden.rb:48:in `call'
> 	 7: from /home/ubuntu/.vagrant.d/gems/2.6.6/gems/vagrant-libvirt-0.1.2/lib/vagrant-libvirt/action/handle_box_image.rb:64:in `call'
> 	 6: from /home/ubuntu/.vagrant.d/gems/2.6.6/gems/vagrant-libvirt-0.1.2/lib/vagrant-libvirt/action/handle_box_image.rb:64:in `synchronize'
> 	 5: from /home/ubuntu/.vagrant.d/gems/2.6.6/gems/vagrant-libvirt-0.1.2/lib/vagrant-libvirt/action/handle_box_image.rb:66:in `block in call'
> 	 4: from /home/ubuntu/.vagrant.d/gems/2.6.6/gems/fog-libvirt-0.7.0/lib/fog/libvirt/models/compute/volumes.rb:11:in `all'
> 	 3: from /home/ubuntu/.vagrant.d/gems/2.6.6/gems/fog-core-2.2.0/lib/fog/core/collection.rb:76:in `load'
> 	 2: from /home/ubuntu/.vagrant.d/gems/2.6.6/gems/fog-core-2.2.0/lib/fog/core/collection.rb:76:in `each'
> 	 1: from /home/ubuntu/.vagrant.d/gems/2.6.6/gems/fog-core-2.2.0/lib/fog/core/collection.rb:76:in `block in load'
> /home/ubuntu/.vagrant.d/gems/2.6.6/gems/fog-core-2.2.0/lib/fog/core/collection.rb:86:in `new': Initialization parameters must be an attributes hash, got NilClass nil (ArgumentError)

**Comment by simonezacca** [comment]
The error can be fixed by restarting libvirtd. Open the terminal and:
`service libvirtd restart`
`/etc/init.d/libvirtd restart`
Now, _vagrant up_ works.

**Comment by ferrarimarco** [comment]
Thanks for the workaround @simonezacca 

I'll leave this open, because we need to investigate further, to at least diagnose the issue.
