### ISSUE TITLE
calico plugin not working

### ISSUE THREAD

**Issue by StefanoSalsano** [ferrarimarco/kubernetes-playground#26]
the installation of the calico networking plugin is apparently successful, but it is not possible to create containers/pod

for example this is not working:
`kubectl run iperf --image=networkstatic/iperf3 --port=5201 -- -s`

kubectl get pods
shows that the operation remains pending and nothing happens on the other nodes

**Comment by StefanoSalsano** [comment]
running sudo docker ps on the minions shows that there is only k8s_POD_calico-node-lbc9n_kube-system_d1 in pause mode and that there is no calico container running

there is a problem with calico configuration and IP addresses

according to
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#pod-network

For Calico to work correctly, you need to pass --pod-network-cidr=192.168.0.0/16 to kubeadm init or update the calico.yaml file to match your Pod network.

we cannot use 192.168.0.0 because it is used by our host network

so we should update the calico.yaml file

I think our CIDR network is 10.96.0.0/12
because in bootstrap-kubernetes-minion.sh I find
kubernetes_cluster_ip_cidr="10.96.0.0/12"

**Comment by ferrarimarco** [comment]
Thanks for the troubleshooting @StefanoSalsano ! Will have a look at this ASAP

**Comment by StefanoSalsano** [comment]
@ferrarimarco : now I made it work (at least I think...) I am preparing a patch

**Comment by ferrarimarco** [comment]
```
            - name: CALICO_IPV4POOL_CIDR
              value: "192.168.0.0/16"
```
That's the bit to update in `calico.yaml`

**Comment by StefanoSalsano** [comment]
yes, I've dowloaded the yaml file and changed this property... I've run everything from scratch and it worked... but the problem is that I forgot to change bootstrap-kubernetes-master.sh
I used the previous configuration file:
kubectl apply -f https://docs.projectcalico.org/v3.10/manifests/calico.yaml

and it worked... so I am trying to understand what was different with respect to previous deployments that were not working... and the problem is that a deployment from scratch takes 45 minutes so it is not easy to make tests :-)

**Comment by StefanoSalsano** [comment]
ok this is the current situation and my understanding
1) I had one deployment in which calico was not working, with the issue reported above
2) I have two deployments in which calico is working using the same calico.yaml, with the "wrong" CIDR 

I think that it is better to change the CIDR and I will try now a new deployment from scratch with the new CIDR in the calico.yaml

I will not investigate further why calico was not working... if it will continue to work consistently

**Comment by StefanoSalsano** [comment]
I think we can close this issue with pull request #29 
the problem with calico not starting in the minions was not depending on these configuration issues... but I think that the networking was not working correctly... by the way we should find some standard way of testing the networking among containers after that the cluster is started and configured

**Comment by ferrarimarco** [comment]
Thanks Stefano! Closing this one. Let's continue the conversation in #29.
