### ISSUE TITLE
Reduce the time needed for provisioning and configuration

### ISSUE THREAD

**Issue by ferrarimarco** [ferrarimarco/kubernetes-playground#31]
The current provisioning and configuration mechanisms suffer from one big issue: they are **SLOW**. This makes fast development iterations unnecessarily hard and cumbersome (you have to make sure everything is idempotent and resilient to reboots).

There are few strategies we could adopt to mitigate this issue. Here's a list of a few that comes to mind

- Leverage pre-build Vagrant boxes: we currently install packages on a bare-bones Vagrant box. We could produce a set of boxes that have the packages we need pre-installed.
  - Pros
    - Reuse the existing infrastructure and tooling (Vagrant + Ansible + Virtualbox...)
    - Cut the provisioning/configuration times
  - Cons
    - More stuff to maintain
    - Unable to automate this using free CI services (see #30 for example)
- Switch to a solution based on Docker (see [kind](https://kind.sigs.k8s.io/) as an example)
  - Pros
    - Cut the provisioning/configuration times
    - Maintained by a K8S SIG
    - Potential increase in test coverage
    - We could use free CI services for the whole stack
  - Cons
    - More complex (is it?) architecture (Kubernetes-in-docker)
    - Harder to represent a scenario that's closer to a real-world use case
    - Need investigation to ensure we can use [Calico](https://alexbrand.dev/post/creating-a-kind-cluster-with-calico-networking/) and [IPv6 networking](https://kind.sigs.k8s.io/docs/user/configuration/#ip-family)

/cc @StefanoSalsano

**Comment by StefanoSalsano** [comment]
I think the first solution "Leverage pre-build Vagrant boxes" could be of great benefit and it should be relatively easy to implement. When running vagrant up from scratch it currently takes 35 minutes. And most of the time is the docker installation. If we have a pre-built machines which lets us skip the installation of docker, docker composer and the basic kubernetes installation
(i.e. until install-kubernetes.sh script) maybe we could go down to 10 minutes which would be good!

**Comment by ferrarimarco** [comment]
Yeah true. What bothers me about the first solution is that we have to take care of the upgrades of such boxes. For example, when a new version of k8s or docker is released, we've to rebuild the boxes. Additionally we also have to track the boxes we use as a base. That's why I was more for a docker-based solution.

I'll update the title of the issue tho

**Comment by ferrarimarco** [comment]
After an offline sync with @StefanoSalsano we are going to explore the following:

1. Split the provisioning and configuration in two steps:
   1. Install the required packages (mainly Docker and Kubernetes)
   1. Bootstrap the Kubernetes cluster

This allows us to avoid wasting time repeating the package installation steps over and over, and we don't have to maintain a Vagrant box. This comes at the cost of dealing with multiple provisioning and configuration steps.

**Comment by ferrarimarco** [comment]
PS: working on this in the `two-steps-provisioning` branch
