### ISSUE TITLE
Switch to a debian-based environment

### ISSUE THREAD

**Issue by ferrarimarco** [ferrarimarco/kubernetes-playground#36]
1. Add the APT repo for Kubernetes in ansible-role-kubernetes
1. Check if Kubernetes package names are the same as RedHat

**Comment by ferrarimarco** [comment]
Candidates:

- Virtualbox: https://app.vagrantup.com/bento/boxes/ubuntu-19.04

@zvfvrv can you look for a suitable libvirt Ubuntu 19.04 box? Thanks!

**Comment by zvfvrv** [comment]
Hi @ferrarimarco, regarding libvirt:

- https://app.vagrantup.com/generic/boxes/ubuntu1904, but the size is 1.23 GB that compared with the one that you are proposing for Virtualbox is too big.

What about a pure Debian? like

-  https://app.vagrantup.com/debian/boxes/buster64, 282 MB

**Comment by ferrarimarco** [comment]
The last one is nice! Supports both virtualbox and libvirt! Definitely worth a try! Thanks.

**Comment by ferrarimarco** [comment]
@StefanoSalsano @zvfvrv are we interested in maintaining support for CentOS? If so, I suppose we should update it to the latest CentOS version. Otherwise, we might just drop it, and switch to Debian.

In my opinion, we can just drop CentOS.

Thoughts?

**Comment by zvfvrv** [comment]
In my opinion we can switch to Debian and drop CentOS

**Comment by StefanoSalsano** [comment]
+1 for dropping CentOS
