### ISSUE TITLE
The Ansible inventory uses IP addresses instead of hostnames

### ISSUE THREAD

**Issue by ferrarimarco** [ferrarimarco/kubernetes-playground#60]
We should use hostnames to avoid dependencies on specific IPs, like we do in `inventory_base`

**Comment by ferrarimarco** [comment]
@zvfvrv this one is harder than it seems :)

We use IP addresses in scripts, in the ansible inventory, and in ansible playbooks (see kubernetes.yml, some `when` conditions use IP addresses).

**Comment by zvfvrv** [comment]
yes just discoverd :D

**Comment by ferrarimarco** [comment]
TODO:

- [ ] Put hostnames in the Ansible inventory file.
- [ ] Use a variable for the `assigned_hostname` key
