### ISSUE TITLE
missing execute permission for files in scripts/linux

### ISSUE THREAD

**Issue by zvfvrv** [ferrarimarco/kubernetes-playground#82]
Starting from a fresh clone seems that the execute permission is missing for files in scripts/linux:

$ ls -la scripts/linux/
total 56
drwxr-xr-x 2 francesco francesco 4096 mar 14 15:17 .
drwxr-xr-x 3 francesco francesco 4096 mar 14 15:17 ..
-rw-r--r-- 1 francesco francesco  400 mar 14 15:17 bootstrap-docker-registry.sh
-rw-r--r-- 1 francesco francesco  585 mar 14 15:17 bootstrap-glusterfs.sh
-rw-r--r-- 1 francesco francesco  567 mar 14 15:17 bootstrap-helm.sh
-rw-r--r-- 1 francesco francesco  221 mar 14 15:17 bootstrap-ingress-controller.sh
-rw-r--r-- 1 francesco francesco 1761 mar 14 15:17 bootstrap-kubernetes-master.sh
-rw-r--r-- 1 francesco francesco  803 mar 14 15:17 bootstrap-kubernetes-minion.sh
-rw-r--r-- 1 francesco francesco  285 mar 14 15:17 bootstrap-monitoring.sh
-rw-r--r-- 1 francesco francesco  256 mar 14 15:17 check-kubeadm-requirements.sh
-rw-r--r-- 1 francesco francesco  801 mar 14 15:17 cleanup-k8s-and-cni.sh
-rw-r--r-- 1 francesco francesco  881 mar 14 15:17 configure-ipv6-interface.sh
-rw-r--r-- 1 francesco francesco  441 mar 14 15:17 install-docker.sh
-rw-r--r-- 1 francesco francesco 1559 mar 14 15:17 install-kubernetes.sh

tested on a Ubuntu 18.04

**Comment by simonezacca** [comment]
I also have the same problem with MacOS Mojave when i start with a clone
