### ISSUE TITLE
CrashLoopBackOff traefik ingress controller

### ISSUE THREAD

**Issue by zvfvrv** [ferrarimarco/kubernetes-playground#94]
I am facing with the following problem, the traefik-ingress-controller pod is in CrashLoopBackOff status

```
[vagrant@k8s-master-1 ~]$ kubectl get pods --all-namespaces
NAMESPACE     NAME                                                  READY   STATUS             RESTARTS   AGE
kube-system   calico-kube-controllers-7489ff5b7c-xnnwd              1/1     Running            0          87m
kube-system   calico-node-8wf5r                                     1/1     Running            0          87m
kube-system   calico-node-fsr25                                     1/1     Running            0          87m
kube-system   calico-node-mxgvv                                     1/1     Running            0          87m
kube-system   calico-node-wxq2c                                     1/1     Running            0          87m
kube-system   coredns-6955765f44-75sbv                              1/1     Running            0          87m
kube-system   coredns-6955765f44-lfffc                              1/1     Running            0          87m
kube-system   etcd-k8s-master-1.k8s-play.local                      1/1     Running            0          87m
kube-system   kube-apiserver-k8s-master-1.k8s-play.local            1/1     Running            0          87m
kube-system   kube-controller-manager-k8s-master-1.k8s-play.local   1/1     Running            0          87m
kube-system   kube-proxy-52n9c                                      1/1     Running            0          87m
kube-system   kube-proxy-dcmbz                                      1/1     Running            0          87m
kube-system   kube-proxy-fdvkw                                      1/1     Running            0          87m
kube-system   kube-proxy-kspwn                                      1/1     Running            0          87m
kube-system   kube-scheduler-k8s-master-1.k8s-play.local            1/1     Running            0          87m
kube-system   traefik-ingress-controller-6499d7f88c-v68c8           0/1     CrashLoopBackOff   11         35m
```

the execution of the deployment script seems ok:

```
[vagrant@k8s-master-1 ~]$ sudo /vagrant/scripts/linux/bootstrap-ingress-controller.sh
secret/traefik-ui-tls-cert created
clusterrole.rbac.authorization.k8s.io/traefik-ingress-controller created
clusterrolebinding.rbac.authorization.k8s.io/traefik-ingress-controller created
serviceaccount/traefik-ingress-controller created
configmap/traefik-ingress-config created
service/traefik-ingress-service created
ingress.networking.k8s.io/traefik-web-ui created
deployment.apps/traefik-ingress-controller created
```

**Comment by ferrarimarco** [comment]
Without further information is difficult to understand what happened. Can you post the pod description (`kubectl describe pod`) and the logs from the failing containers?

**Comment by zvfvrv** [comment]
ok the logs are the following
[vagrant@k8s-master-1 ~]$ kubectl logs -f traefik-ingress-controller-6499d7f88c-v68c8 -c traefik-ingress-lb -n kube-system
2020/03/19 18:14:44 command traefik error: field not found, node: tls

regarding the output of  the command` kubectl describe pod` please find file attached here [pod_describe.log](https://github.com/ferrarimarco/kubernetes-playground/files/4356306/pod_describe.log)

**Comment by ferrarimarco** [comment]
Can you also post the container logs? `kubectl get logs ...`

**Comment by zvfvrv** [comment]
Hi @ferrarimarco, but the logs of the container are the following

> [vagrant@k8s-master-1 ~]$ kubectl logs -f traefik-ingress-controller-6499d7f88c-v68c8 -c traefik-ingress-lb -n kube-system
2020/03/19 18:14:44 command traefik error: field not found, node: tls

seems that` kubectl get logs ...` is not a valid command i guess

**Comment by ferrarimarco** [comment]
I guess there's something off with `traefik.toml` config file, defined in [kubernetes/traefik/01-configmap.yaml. Can you check which Traefik version you're currently running? Maybe they changed the format somehow, and I didn't use a fixed image tag :(

**Comment by ferrarimarco** [comment]
Yes, that must be the reason. I guess you're currently running Traefik 2.x right?

https://docs.traefik.io/migration/v1-to-v2

**Comment by ferrarimarco** [comment]
Can you try with the `v1.7.22` docker image? Just edit the Deployment.

**Comment by zvfvrv** [comment]
@ferrarimarco  yes with`v1.7.22` works fine

**Comment by ferrarimarco** [comment]
Can you open a PR with the fix? Thanks!

>
