### ISSUE TITLE
The additional disk cannot be created in WSL

### ISSUE THREAD

**Issue by ferrarimarco** [ferrarimarco/kubernetes-playground#98]
The mechanism we're currently using to create an additional disk doesn't work if you run Vagrant in WSL, because the Virtualbox provisioner (that is installed on Windows) uses Windows paths.

```shell
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["createmedium", "disk", "--filename", "/mnt/c/Users/XXXXX/workspaces/kubernetes-playground/base-box-builder.k8s-play.local-disk-2.vmdk", "--size", "10240", "--format", "VMDK"]

Stderr: 0%...
Progress state: VBOX_E_FILE_ERROR
VBoxManage.exe: error: Failed to create medium
VBoxManage.exe: error: Could not create the medium storage unit 'C:\mnt\c\Users\XXXXX\workspaces\kubernetes-playground\base-box-builder.k8s-play.local-disk-2.vmdk'.
VBoxManage.exe: error: VMDK: could not create new file 'C:\mnt\c\Users\XXXXX\workspaces\kubernetes-playground\base-box-builder.k8s-play.local-disk-2.vmdk' (VERR_ALREADY_EXISTS)
VBoxManage.exe: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component MediumWrap, interface IMedium
VBoxManage.exe: error: Context: "enum RTEXITCODE __cdecl handleCreateMedium(struct HandlerArg *)" at line 510 of file VBoxManageDisk.cpp
```

**Comment by ferrarimarco** [comment]
The issue is how we calculate the path to where Virtualbox stores VMs.

`vm_info = driver.execute("showvminfo", uuid, "--machinereadable")` actually runs in Windows, not in WSL, so the information it returns is relevant for Windows. We're interested in the VM path on disk only, so we should adapt that path to our needs, if running in WSL.

**Comment by StefanoSalsano** [comment]
just for curiosity... do you have a particular interest on WSL?
do you know how much it is spread out?
have you heard of someone interested in it?

**Comment by ferrarimarco** [comment]
Yes, me! I'm using WSL because it's just easier to use the same toolchain (where possible), regardless of the OS.

Besides this, I don't have any real usage stats. I know that Microsoft is working hard on that (WSL 2 GA includes a Linux kernel, so (almost) no emulation!).

**Comment by ferrarimarco** [comment]
And considering the numbers of https://github.com/microsoft/WSL, it's definetly not a niche product.
